# Use postgres/example user/password credentials
version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: rodrigo
      POSTGRES_PASSWORD: 3155856558
      POSTGRES_DB: spring_db_v1
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data
